'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.0.3705.288
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Data
Imports System.Runtime.Serialization
Imports System.Xml


<Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Diagnostics.DebuggerStepThrough(),  _
 System.ComponentModel.ToolboxItem(true)>  _
Public Class dsExam
    Inherits DataSet
    
    Private tableQ1 As Q1DataTable
    
    Public Sub New()
        MyBase.New
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    Protected Sub New(ByVal info As SerializationInfo, ByVal context As StreamingContext)
        MyBase.New
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(System.String)),String)
        If (Not (strSchema) Is Nothing) Then
            Dim ds As DataSet = New DataSet
            ds.ReadXmlSchema(New XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("Q1")) Is Nothing) Then
                Me.Tables.Add(New Q1DataTable(ds.Tables("Q1")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.InitClass
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property Q1 As Q1DataTable
        Get
            Return Me.tableQ1
        End Get
    End Property
    
    Public Overrides Function Clone() As DataSet
        Dim cln As dsExam = CType(MyBase.Clone,dsExam)
        cln.InitVars
        Return cln
    End Function
    
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As XmlReader)
        Me.Reset
        Dim ds As DataSet = New DataSet
        ds.ReadXml(reader)
        If (Not (ds.Tables("Q1")) Is Nothing) Then
            Me.Tables.Add(New Q1DataTable(ds.Tables("Q1")))
        End If
        Me.DataSetName = ds.DataSetName
        Me.Prefix = ds.Prefix
        Me.Namespace = ds.Namespace
        Me.Locale = ds.Locale
        Me.CaseSensitive = ds.CaseSensitive
        Me.EnforceConstraints = ds.EnforceConstraints
        Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
        Me.InitVars
    End Sub
    
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New XmlTextReader(stream), Nothing)
    End Function
    
    Friend Sub InitVars()
        Me.tableQ1 = CType(Me.Tables("Q1"),Q1DataTable)
        If (Not (Me.tableQ1) Is Nothing) Then
            Me.tableQ1.InitVars
        End If
    End Sub
    
    Private Sub InitClass()
        Me.DataSetName = "dsExam"
        Me.Prefix = ""
        Me.Namespace = "http://www.tempuri.org/dsExam.xsd"
        Me.Locale = New System.Globalization.CultureInfo("en-US")
        Me.CaseSensitive = false
        Me.EnforceConstraints = true
        Me.tableQ1 = New Q1DataTable
        Me.Tables.Add(Me.tableQ1)
    End Sub
    
    Private Function ShouldSerializeQ1() As Boolean
        Return false
    End Function
    
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    Public Delegate Sub Q1RowChangeEventHandler(ByVal sender As Object, ByVal e As Q1RowChangeEvent)
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class Q1DataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columnQID As DataColumn
        
        Private columnQues As DataColumn
        
        Private columnAns2 As DataColumn
        
        Private columnAns1 As DataColumn
        
        Private columnAns3 As DataColumn
        
        Private columnAns4 As DataColumn
        
        Private columnAns5 As DataColumn
        
        Private columnAns6 As DataColumn
        
        Private columnAns7 As DataColumn
        
        Private columnAnsA As DataColumn
        
        Private columnAnsB As DataColumn
        
        Private columnAnsC As DataColumn
        
        Private columnAnsD As DataColumn
        
        Private columnAnsE As DataColumn
        
        Private columnAnsF As DataColumn
        
        Private columnAnsG As DataColumn
        
        Private columnAnswer As DataColumn
        
        Private columnchkoropt As DataColumn
        
        Private columnExhibit As DataColumn
        
        Private columnExhibitName As DataColumn
        
        Private columnExplanation As DataColumn
        
        Private columnInputAnswer As DataColumn
        
        Private columnInputAnswer2 As DataColumn
        
        Friend Sub New()
            MyBase.New("Q1")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property QIDColumn As DataColumn
            Get
                Return Me.columnQID
            End Get
        End Property
        
        Friend ReadOnly Property QuesColumn As DataColumn
            Get
                Return Me.columnQues
            End Get
        End Property
        
        Friend ReadOnly Property Ans2Column As DataColumn
            Get
                Return Me.columnAns2
            End Get
        End Property
        
        Friend ReadOnly Property Ans1Column As DataColumn
            Get
                Return Me.columnAns1
            End Get
        End Property
        
        Friend ReadOnly Property Ans3Column As DataColumn
            Get
                Return Me.columnAns3
            End Get
        End Property
        
        Friend ReadOnly Property Ans4Column As DataColumn
            Get
                Return Me.columnAns4
            End Get
        End Property
        
        Friend ReadOnly Property Ans5Column As DataColumn
            Get
                Return Me.columnAns5
            End Get
        End Property
        
        Friend ReadOnly Property Ans6Column As DataColumn
            Get
                Return Me.columnAns6
            End Get
        End Property
        
        Friend ReadOnly Property Ans7Column As DataColumn
            Get
                Return Me.columnAns7
            End Get
        End Property
        
        Friend ReadOnly Property AnsAColumn As DataColumn
            Get
                Return Me.columnAnsA
            End Get
        End Property
        
        Friend ReadOnly Property AnsBColumn As DataColumn
            Get
                Return Me.columnAnsB
            End Get
        End Property
        
        Friend ReadOnly Property AnsCColumn As DataColumn
            Get
                Return Me.columnAnsC
            End Get
        End Property
        
        Friend ReadOnly Property AnsDColumn As DataColumn
            Get
                Return Me.columnAnsD
            End Get
        End Property
        
        Friend ReadOnly Property AnsEColumn As DataColumn
            Get
                Return Me.columnAnsE
            End Get
        End Property
        
        Friend ReadOnly Property AnsFColumn As DataColumn
            Get
                Return Me.columnAnsF
            End Get
        End Property
        
        Friend ReadOnly Property AnsGColumn As DataColumn
            Get
                Return Me.columnAnsG
            End Get
        End Property
        
        Friend ReadOnly Property AnswerColumn As DataColumn
            Get
                Return Me.columnAnswer
            End Get
        End Property
        
        Friend ReadOnly Property chkoroptColumn As DataColumn
            Get
                Return Me.columnchkoropt
            End Get
        End Property
        
        Friend ReadOnly Property ExhibitColumn As DataColumn
            Get
                Return Me.columnExhibit
            End Get
        End Property
        
        Friend ReadOnly Property ExhibitNameColumn As DataColumn
            Get
                Return Me.columnExhibitName
            End Get
        End Property
        
        Friend ReadOnly Property ExplanationColumn As DataColumn
            Get
                Return Me.columnExplanation
            End Get
        End Property
        
        Friend ReadOnly Property InputAnswerColumn As DataColumn
            Get
                Return Me.columnInputAnswer
            End Get
        End Property
        
        Friend ReadOnly Property InputAnswer2Column As DataColumn
            Get
                Return Me.columnInputAnswer2
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As Q1Row
            Get
                Return CType(Me.Rows(index),Q1Row)
            End Get
        End Property
        
        Public Event Q1RowChanged As Q1RowChangeEventHandler
        
        Public Event Q1RowChanging As Q1RowChangeEventHandler
        
        Public Event Q1RowDeleted As Q1RowChangeEventHandler
        
        Public Event Q1RowDeleting As Q1RowChangeEventHandler
        
        Public Overloads Sub AddQ1Row(ByVal row As Q1Row)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AddQ1Row( _
                    ByVal QID As Short,  _
                    ByVal Ques As String,  _
                    ByVal Ans2 As Short,  _
                    ByVal Ans1 As Short,  _
                    ByVal Ans3 As Short,  _
                    ByVal Ans4 As Short,  _
                    ByVal Ans5 As Short,  _
                    ByVal Ans6 As Short,  _
                    ByVal Ans7 As Short,  _
                    ByVal AnsA As String,  _
                    ByVal AnsB As String,  _
                    ByVal AnsC As String,  _
                    ByVal AnsD As String,  _
                    ByVal AnsE As String,  _
                    ByVal AnsF As String,  _
                    ByVal AnsG As String,  _
                    ByVal Answer As String,  _
                    ByVal chkoropt As String,  _
                    ByVal Exhibit As String,  _
                    ByVal ExhibitName As String,  _
                    ByVal Explanation As String,  _
                    ByVal InputAnswer As String,  _
                    ByVal InputAnswer2 As String) As Q1Row
            Dim rowQ1Row As Q1Row = CType(Me.NewRow,Q1Row)
            rowQ1Row.ItemArray = New Object() {QID, Ques, Ans2, Ans1, Ans3, Ans4, Ans5, Ans6, Ans7, AnsA, AnsB, AnsC, AnsD, AnsE, AnsF, AnsG, Answer, chkoropt, Exhibit, ExhibitName, Explanation, InputAnswer, InputAnswer2}
            Me.Rows.Add(rowQ1Row)
            Return rowQ1Row
        End Function
        
        Public Function FindByQID(ByVal QID As Short) As Q1Row
            Return CType(Me.Rows.Find(New Object() {QID}),Q1Row)
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As Q1DataTable = CType(MyBase.Clone,Q1DataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New Q1DataTable
        End Function
        
        Friend Sub InitVars()
            Me.columnQID = Me.Columns("QID")
            Me.columnQues = Me.Columns("Ques")
            Me.columnAns2 = Me.Columns("Ans2")
            Me.columnAns1 = Me.Columns("Ans1")
            Me.columnAns3 = Me.Columns("Ans3")
            Me.columnAns4 = Me.Columns("Ans4")
            Me.columnAns5 = Me.Columns("Ans5")
            Me.columnAns6 = Me.Columns("Ans6")
            Me.columnAns7 = Me.Columns("Ans7")
            Me.columnAnsA = Me.Columns("AnsA")
            Me.columnAnsB = Me.Columns("AnsB")
            Me.columnAnsC = Me.Columns("AnsC")
            Me.columnAnsD = Me.Columns("AnsD")
            Me.columnAnsE = Me.Columns("AnsE")
            Me.columnAnsF = Me.Columns("AnsF")
            Me.columnAnsG = Me.Columns("AnsG")
            Me.columnAnswer = Me.Columns("Answer")
            Me.columnchkoropt = Me.Columns("chkoropt")
            Me.columnExhibit = Me.Columns("Exhibit")
            Me.columnExhibitName = Me.Columns("ExhibitName")
            Me.columnExplanation = Me.Columns("Explanation")
            Me.columnInputAnswer = Me.Columns("InputAnswer")
            Me.columnInputAnswer2 = Me.Columns("InputAnswer2")
        End Sub
        
        Private Sub InitClass()
            Me.columnQID = New DataColumn("QID", GetType(System.Int16), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnQID)
            Me.columnQues = New DataColumn("Ques", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnQues)
            Me.columnAns2 = New DataColumn("Ans2", GetType(System.Int16), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnAns2)
            Me.columnAns1 = New DataColumn("Ans1", GetType(System.Int16), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnAns1)
            Me.columnAns3 = New DataColumn("Ans3", GetType(System.Int16), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnAns3)
            Me.columnAns4 = New DataColumn("Ans4", GetType(System.Int16), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnAns4)
            Me.columnAns5 = New DataColumn("Ans5", GetType(System.Int16), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnAns5)
            Me.columnAns6 = New DataColumn("Ans6", GetType(System.Int16), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnAns6)
            Me.columnAns7 = New DataColumn("Ans7", GetType(System.Int16), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnAns7)
            Me.columnAnsA = New DataColumn("AnsA", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnAnsA)
            Me.columnAnsB = New DataColumn("AnsB", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnAnsB)
            Me.columnAnsC = New DataColumn("AnsC", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnAnsC)
            Me.columnAnsD = New DataColumn("AnsD", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnAnsD)
            Me.columnAnsE = New DataColumn("AnsE", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnAnsE)
            Me.columnAnsF = New DataColumn("AnsF", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnAnsF)
            Me.columnAnsG = New DataColumn("AnsG", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnAnsG)
            Me.columnAnswer = New DataColumn("Answer", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnAnswer)
            Me.columnchkoropt = New DataColumn("chkoropt", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnchkoropt)
            Me.columnExhibit = New DataColumn("Exhibit", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnExhibit)
            Me.columnExhibitName = New DataColumn("ExhibitName", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnExhibitName)
            Me.columnExplanation = New DataColumn("Explanation", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnExplanation)
            Me.columnInputAnswer = New DataColumn("InputAnswer", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnInputAnswer)
            Me.columnInputAnswer2 = New DataColumn("InputAnswer2", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnInputAnswer2)
            Me.Constraints.Add(New UniqueConstraint("Constraint1", New DataColumn() {Me.columnQID}, true))
            Me.columnQID.AllowDBNull = false
            Me.columnQID.Unique = true
        End Sub
        
        Public Function NewQ1Row() As Q1Row
            Return CType(Me.NewRow,Q1Row)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New Q1Row(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(Q1Row)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.Q1RowChangedEvent) Is Nothing) Then
                RaiseEvent Q1RowChanged(Me, New Q1RowChangeEvent(CType(e.Row,Q1Row), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.Q1RowChangingEvent) Is Nothing) Then
                RaiseEvent Q1RowChanging(Me, New Q1RowChangeEvent(CType(e.Row,Q1Row), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.Q1RowDeletedEvent) Is Nothing) Then
                RaiseEvent Q1RowDeleted(Me, New Q1RowChangeEvent(CType(e.Row,Q1Row), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.Q1RowDeletingEvent) Is Nothing) Then
                RaiseEvent Q1RowDeleting(Me, New Q1RowChangeEvent(CType(e.Row,Q1Row), e.Action))
            End If
        End Sub
        
        Public Sub RemoveQ1Row(ByVal row As Q1Row)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class Q1Row
        Inherits DataRow
        
        Private tableQ1 As Q1DataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tableQ1 = CType(Me.Table,Q1DataTable)
        End Sub
        
        Public Property QID As Short
            Get
                Return CType(Me(Me.tableQ1.QIDColumn),Short)
            End Get
            Set
                Me(Me.tableQ1.QIDColumn) = value
            End Set
        End Property
        
        Public Property Ques As String
            Get
                Try 
                    Return CType(Me(Me.tableQ1.QuesColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableQ1.QuesColumn) = value
            End Set
        End Property
        
        Public Property Ans2 As Short
            Get
                Try 
                    Return CType(Me(Me.tableQ1.Ans2Column),Short)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableQ1.Ans2Column) = value
            End Set
        End Property
        
        Public Property Ans1 As Short
            Get
                Try 
                    Return CType(Me(Me.tableQ1.Ans1Column),Short)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableQ1.Ans1Column) = value
            End Set
        End Property
        
        Public Property Ans3 As Short
            Get
                Try 
                    Return CType(Me(Me.tableQ1.Ans3Column),Short)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableQ1.Ans3Column) = value
            End Set
        End Property
        
        Public Property Ans4 As Short
            Get
                Try 
                    Return CType(Me(Me.tableQ1.Ans4Column),Short)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableQ1.Ans4Column) = value
            End Set
        End Property
        
        Public Property Ans5 As Short
            Get
                Try 
                    Return CType(Me(Me.tableQ1.Ans5Column),Short)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableQ1.Ans5Column) = value
            End Set
        End Property
        
        Public Property Ans6 As Short
            Get
                Try 
                    Return CType(Me(Me.tableQ1.Ans6Column),Short)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableQ1.Ans6Column) = value
            End Set
        End Property
        
        Public Property Ans7 As Short
            Get
                Try 
                    Return CType(Me(Me.tableQ1.Ans7Column),Short)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableQ1.Ans7Column) = value
            End Set
        End Property
        
        Public Property AnsA As String
            Get
                Try 
                    Return CType(Me(Me.tableQ1.AnsAColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableQ1.AnsAColumn) = value
            End Set
        End Property
        
        Public Property AnsB As String
            Get
                Try 
                    Return CType(Me(Me.tableQ1.AnsBColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableQ1.AnsBColumn) = value
            End Set
        End Property
        
        Public Property AnsC As String
            Get
                Try 
                    Return CType(Me(Me.tableQ1.AnsCColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableQ1.AnsCColumn) = value
            End Set
        End Property
        
        Public Property AnsD As String
            Get
                Try 
                    Return CType(Me(Me.tableQ1.AnsDColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableQ1.AnsDColumn) = value
            End Set
        End Property
        
        Public Property AnsE As String
            Get
                Try 
                    Return CType(Me(Me.tableQ1.AnsEColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableQ1.AnsEColumn) = value
            End Set
        End Property
        
        Public Property AnsF As String
            Get
                Try 
                    Return CType(Me(Me.tableQ1.AnsFColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableQ1.AnsFColumn) = value
            End Set
        End Property
        
        Public Property AnsG As String
            Get
                Try 
                    Return CType(Me(Me.tableQ1.AnsGColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableQ1.AnsGColumn) = value
            End Set
        End Property
        
        Public Property Answer As String
            Get
                Try 
                    Return CType(Me(Me.tableQ1.AnswerColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableQ1.AnswerColumn) = value
            End Set
        End Property
        
        Public Property chkoropt As String
            Get
                Try 
                    Return CType(Me(Me.tableQ1.chkoroptColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableQ1.chkoroptColumn) = value
            End Set
        End Property
        
        Public Property Exhibit As String
            Get
                Try 
                    Return CType(Me(Me.tableQ1.ExhibitColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableQ1.ExhibitColumn) = value
            End Set
        End Property
        
        Public Property ExhibitName As String
            Get
                Try 
                    Return CType(Me(Me.tableQ1.ExhibitNameColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableQ1.ExhibitNameColumn) = value
            End Set
        End Property
        
        Public Property Explanation As String
            Get
                Try 
                    Return CType(Me(Me.tableQ1.ExplanationColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableQ1.ExplanationColumn) = value
            End Set
        End Property
        
        Public Property InputAnswer As String
            Get
                Try 
                    Return CType(Me(Me.tableQ1.InputAnswerColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableQ1.InputAnswerColumn) = value
            End Set
        End Property
        
        Public Property InputAnswer2 As String
            Get
                Try 
                    Return CType(Me(Me.tableQ1.InputAnswer2Column),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableQ1.InputAnswer2Column) = value
            End Set
        End Property
        
        Public Function IsQuesNull() As Boolean
            Return Me.IsNull(Me.tableQ1.QuesColumn)
        End Function
        
        Public Sub SetQuesNull()
            Me(Me.tableQ1.QuesColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsAns2Null() As Boolean
            Return Me.IsNull(Me.tableQ1.Ans2Column)
        End Function
        
        Public Sub SetAns2Null()
            Me(Me.tableQ1.Ans2Column) = System.Convert.DBNull
        End Sub
        
        Public Function IsAns1Null() As Boolean
            Return Me.IsNull(Me.tableQ1.Ans1Column)
        End Function
        
        Public Sub SetAns1Null()
            Me(Me.tableQ1.Ans1Column) = System.Convert.DBNull
        End Sub
        
        Public Function IsAns3Null() As Boolean
            Return Me.IsNull(Me.tableQ1.Ans3Column)
        End Function
        
        Public Sub SetAns3Null()
            Me(Me.tableQ1.Ans3Column) = System.Convert.DBNull
        End Sub
        
        Public Function IsAns4Null() As Boolean
            Return Me.IsNull(Me.tableQ1.Ans4Column)
        End Function
        
        Public Sub SetAns4Null()
            Me(Me.tableQ1.Ans4Column) = System.Convert.DBNull
        End Sub
        
        Public Function IsAns5Null() As Boolean
            Return Me.IsNull(Me.tableQ1.Ans5Column)
        End Function
        
        Public Sub SetAns5Null()
            Me(Me.tableQ1.Ans5Column) = System.Convert.DBNull
        End Sub
        
        Public Function IsAns6Null() As Boolean
            Return Me.IsNull(Me.tableQ1.Ans6Column)
        End Function
        
        Public Sub SetAns6Null()
            Me(Me.tableQ1.Ans6Column) = System.Convert.DBNull
        End Sub
        
        Public Function IsAns7Null() As Boolean
            Return Me.IsNull(Me.tableQ1.Ans7Column)
        End Function
        
        Public Sub SetAns7Null()
            Me(Me.tableQ1.Ans7Column) = System.Convert.DBNull
        End Sub
        
        Public Function IsAnsANull() As Boolean
            Return Me.IsNull(Me.tableQ1.AnsAColumn)
        End Function
        
        Public Sub SetAnsANull()
            Me(Me.tableQ1.AnsAColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsAnsBNull() As Boolean
            Return Me.IsNull(Me.tableQ1.AnsBColumn)
        End Function
        
        Public Sub SetAnsBNull()
            Me(Me.tableQ1.AnsBColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsAnsCNull() As Boolean
            Return Me.IsNull(Me.tableQ1.AnsCColumn)
        End Function
        
        Public Sub SetAnsCNull()
            Me(Me.tableQ1.AnsCColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsAnsDNull() As Boolean
            Return Me.IsNull(Me.tableQ1.AnsDColumn)
        End Function
        
        Public Sub SetAnsDNull()
            Me(Me.tableQ1.AnsDColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsAnsENull() As Boolean
            Return Me.IsNull(Me.tableQ1.AnsEColumn)
        End Function
        
        Public Sub SetAnsENull()
            Me(Me.tableQ1.AnsEColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsAnsFNull() As Boolean
            Return Me.IsNull(Me.tableQ1.AnsFColumn)
        End Function
        
        Public Sub SetAnsFNull()
            Me(Me.tableQ1.AnsFColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsAnsGNull() As Boolean
            Return Me.IsNull(Me.tableQ1.AnsGColumn)
        End Function
        
        Public Sub SetAnsGNull()
            Me(Me.tableQ1.AnsGColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsAnswerNull() As Boolean
            Return Me.IsNull(Me.tableQ1.AnswerColumn)
        End Function
        
        Public Sub SetAnswerNull()
            Me(Me.tableQ1.AnswerColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IschkoroptNull() As Boolean
            Return Me.IsNull(Me.tableQ1.chkoroptColumn)
        End Function
        
        Public Sub SetchkoroptNull()
            Me(Me.tableQ1.chkoroptColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsExhibitNull() As Boolean
            Return Me.IsNull(Me.tableQ1.ExhibitColumn)
        End Function
        
        Public Sub SetExhibitNull()
            Me(Me.tableQ1.ExhibitColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsExhibitNameNull() As Boolean
            Return Me.IsNull(Me.tableQ1.ExhibitNameColumn)
        End Function
        
        Public Sub SetExhibitNameNull()
            Me(Me.tableQ1.ExhibitNameColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsExplanationNull() As Boolean
            Return Me.IsNull(Me.tableQ1.ExplanationColumn)
        End Function
        
        Public Sub SetExplanationNull()
            Me(Me.tableQ1.ExplanationColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsInputAnswerNull() As Boolean
            Return Me.IsNull(Me.tableQ1.InputAnswerColumn)
        End Function
        
        Public Sub SetInputAnswerNull()
            Me(Me.tableQ1.InputAnswerColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsInputAnswer2Null() As Boolean
            Return Me.IsNull(Me.tableQ1.InputAnswer2Column)
        End Function
        
        Public Sub SetInputAnswer2Null()
            Me(Me.tableQ1.InputAnswer2Column) = System.Convert.DBNull
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class Q1RowChangeEvent
        Inherits EventArgs
        
        Private eventRow As Q1Row
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As Q1Row, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As Q1Row
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
