public enum FrameStones
    {
        Frame_Flat_1_Gang_Stones = 6,
        Frame_Decorz_1_Gang_Stones = 6,
        Frame_Decorz_2_Gang_Stones = 12,
        Frame_Decorz_3_Gang_Stones = 18,
        Frame_Decorz_4_Gang_Stones = 24,
        Frame_Flat_2_Gang_Stones = 12,
        Frame_1Gang_LVMB_DECORZ_Stones = 6,
        Frame_2Gang_Round_Stones = 6,
        Frame_2Gang_Special_SVGA4_Stones = 4,
        Frame_2Gang_Special_X_Stones = 6,
        Frame_2Gang_Special_SVGASVGA4_Stones = 8,
        Frame_2Gang_SVGA4_X_Stones = 10,
        Frame_3Gang_Special_XX_Stones = 12,
        Frame_3Gang_SpecialSpecialX_Stones = 6,
        Frame_4gang_SSSX_Stones = 6,
        Frame_4gang_SSXX_Stones = 12,
        Frame_4gang_SXXX_Stones = 18,
        Frame_Dongle_Decorz_Stones = 6,
        Frame_Dongle_Flat_Stones = 6,
        Frame_Insert_1G_Stones = 6,
        Frame_Insert_2G_Stones = 12,
        Frame_Insert_3G_Stones = 18,
        Frame_Insert_4G_Stones = 24,
        Frame_svga_rca_Stones = 2,
        Frame_SVGA_1GANG_Stones = 4,

    }